import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Eye, Search } from 'lucide-react'
import { useDeferredValue, useState } from 'react'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import { getCustomers } from '../api/customers'
import { getInvoices, markInvoicePaid } from '../api/invoices'
import { PageHeader } from '../components/PageHeader'
import { EmptyState, ErrorState, LoadingBlock } from '../components/StateViews'
import { StatusBadge } from '../components/StatusBadge'
import { Button } from '../components/ui/button'
import { Card, CardContent } from '../components/ui/card'
import { Input } from '../components/ui/input'
import { Label } from '../components/ui/label'
import { Select } from '../components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../components/ui/table'
import { useAuth } from '../auth/useAuth'
import { getApiErrorMessage } from '../lib/apiClient'
import { formatDate, formatMoney } from '../lib/format'
import { canMarkInvoicePaid } from '../lib/permissions'
import type { InvoiceStatus } from '../types'

const invoiceStatuses: (InvoiceStatus | '')[] = ['', 'Issued', 'Paid', 'Cancelled']

export function InvoiceListPage() {
  const { user } = useAuth()
  const queryClient = useQueryClient()
  const [search, setSearch] = useState('')
  const deferredSearch = useDeferredValue(search)
  const [status, setStatus] = useState<InvoiceStatus | ''>('')
  const [customerId, setCustomerId] = useState('')
  const invoicesQuery = useQuery({
    queryKey: ['invoices', { status, customerId, search: deferredSearch }],
    queryFn: () => getInvoices({ status, customerId, search: deferredSearch, pageSize: 50 }),
  })
  const customersQuery = useQuery({ queryKey: ['customers'], queryFn: getCustomers })
  const markPaidMutation = useMutation({
    mutationFn: markInvoicePaid,
    onSuccess: async () => {
      toast.success('Invoice marked as paid.')
      await queryClient.invalidateQueries({ queryKey: ['invoices'] })
      await queryClient.invalidateQueries({ queryKey: ['billing-requests'] })
      await queryClient.invalidateQueries({ queryKey: ['dashboard-summary'] })
    },
    onError: (error) => toast.error(getApiErrorMessage(error, 'Invoice could not be marked as paid.')),
  })
  const invoices = invoicesQuery.data?.items ?? []

  return (
    <>
      <PageHeader title="Invoices" description="Review issued and paid invoices generated by approved billing requests." />

      <Card className="mb-4">
        <CardContent className="grid gap-4 p-4 md:grid-cols-3">
          <div className="space-y-2">
            <Label htmlFor="invoice-search">Search</Label>
            <div className="relative">
              <Search className="absolute left-3 top-3 h-4 w-4 text-slate-500" aria-hidden="true" />
              <Input id="invoice-search" className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="invoice-status">Status</Label>
            <Select id="invoice-status" value={status} onChange={(event) => setStatus(event.target.value as InvoiceStatus | '')}>
              {invoiceStatuses.map((item) => (
                <option key={item || 'all'} value={item}>
                  {item || 'All statuses'}
                </option>
              ))}
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="invoice-customer">Customer</Label>
            <Select id="invoice-customer" value={customerId} onChange={(event) => setCustomerId(event.target.value)}>
              <option value="">All customers</option>
              {customersQuery.data?.map((customer) => (
                <option key={customer.id} value={customer.id}>
                  {customer.name}
                </option>
              ))}
            </Select>
          </div>
        </CardContent>
      </Card>

      {invoicesQuery.isLoading ? <LoadingBlock /> : null}
      {invoicesQuery.isError ? <ErrorState message="Invoices could not be loaded." onRetry={() => void invoicesQuery.refetch()} /> : null}
      {!invoicesQuery.isLoading && !invoicesQuery.isError && invoices.length === 0 ? (
        <EmptyState title="No invoices found" message="Approved requests will generate invoices here." />
      ) : null}
      {invoices.length > 0 ? (
        <Card>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Invoice No</TableHead>
                  <TableHead>Request No</TableHead>
                  <TableHead>Customer</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead>Issued</TableHead>
                  <TableHead>Due</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {invoices.map((invoice) => (
                  <TableRow key={invoice.id}>
                    <TableCell className="font-semibold text-slate-950">{invoice.invoiceNumber}</TableCell>
                    <TableCell>{invoice.billingRequestNumber}</TableCell>
                    <TableCell>{invoice.customerName}</TableCell>
                    <TableCell>
                      <StatusBadge status={invoice.status} />
                    </TableCell>
                    <TableCell>{formatMoney(invoice.totalAmount)}</TableCell>
                    <TableCell>{formatDate(invoice.issuedAtUtc)}</TableCell>
                    <TableCell>{formatDate(invoice.dueAtUtc)}</TableCell>
                    <TableCell>
                      <div className="flex justify-end gap-2">
                        <Button asChild variant="outline" size="sm">
                          <Link to={`/app/invoices/${invoice.id}`}>
                            <Eye className="h-4 w-4" aria-hidden="true" />
                            View
                          </Link>
                        </Button>
                        {user && canMarkInvoicePaid(user.role, invoice.status) ? (
                          <Button size="sm" onClick={() => markPaidMutation.mutate(invoice.id)} disabled={markPaidMutation.isPending}>
                            Mark Paid
                          </Button>
                        ) : null}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </Card>
      ) : null}
    </>
  )
}
