// <auto-generated />
using System;
using FlowLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowLedgerDbContext))]
    [Migration("20260613113616_AddUserPreferences")]
    partial class AddUserPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowLedger.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "Jwt.AccessTokenMinutes",
                            Description = "Access token lifetime in minutes.",
                            Value = "30"
                        },
                        new
                        {
                            Key = "Billing.VatPercentage",
                            Description = "VAT percentage used for new billing request totals.",
                            Value = "15"
                        },
                        new
                        {
                            Key = "Billing.ManagerApprovalThreshold",
                            Description = "Total amount above which Accounts approval routes to Management.",
                            Value = "100000"
                        },
                        new
                        {
                            Key = "Billing.InvoiceDueDays",
                            Description = "Number of days after issue date used for new invoice due dates.",
                            Value = "30"
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BeforeStatus")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("BillingRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("BillingRequestId", "CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc");

                    b.ToTable("AuditLogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000001"),
                            ActionType = 1,
                            ActorDisplayName = "Sarah Sales",
                            ActorUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("99999999-9999-9999-9999-000000000001"),
                            EntityNumber = "BR-2026-0001",
                            EntityType = "BillingRequest",
                            Message = "Billing request created."
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000002"),
                            ActionType = 3,
                            ActorDisplayName = "Sarah Sales",
                            ActorUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 1, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("99999999-9999-9999-9999-000000000004"),
                            EntityNumber = "BR-2026-0004",
                            EntityType = "BillingRequest",
                            Message = "Billing request submitted to Accounts."
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000003"),
                            ActionType = 3,
                            ActorDisplayName = "Sarah Sales",
                            ActorUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 1, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("99999999-9999-9999-9999-000000000006"),
                            EntityNumber = "BR-2026-0006",
                            EntityType = "BillingRequest",
                            Message = "Billing request submitted to Accounts."
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000004"),
                            ActionType = 5,
                            ActorDisplayName = "Amir Accounts",
                            ActorUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 1, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("99999999-9999-9999-9999-000000000008"),
                            EntityNumber = "BR-2026-0008",
                            EntityType = "BillingRequest",
                            Message = "Accounts rejected request for revision."
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000005"),
                            ActionType = 7,
                            ActorDisplayName = "Amir Accounts",
                            ActorUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 1, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("99999999-9999-9999-9999-000000000010"),
                            EntityNumber = "BR-2026-0010",
                            EntityType = "BillingRequest",
                            Message = "Invoice generated after Accounts approval."
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000006"),
                            ActionType = 8,
                            ActorDisplayName = "Amir Accounts",
                            ActorUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000014"),
                            CreatedAtUtc = new DateTime(2026, 1, 19, 11, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("99999999-9999-9999-9999-000000000014"),
                            EntityNumber = "BR-2026-0014",
                            EntityType = "BillingRequest",
                            Message = "Invoice marked as paid."
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.BillingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountsReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedQueue")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastWorkflowActionAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ManagerReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedQueue");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("BillingRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000001"),
                            AssignedAtUtc = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Description = "Retail starter billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0001",
                            Status = 1,
                            SubtotalAmount = 10434.78m,
                            Title = "Retail starter billing",
                            TotalAmount = 12000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 1565.22m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000002"),
                            AssignedAtUtc = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Description = "Monthly logistics support for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0002",
                            Status = 1,
                            SubtotalAmount = 67826.09m,
                            Title = "Monthly logistics support",
                            TotalAmount = 78000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 10173.91m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000003"),
                            AssignedAtUtc = new DateTime(2026, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 2,
                            AssignedToUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTime(2026, 1, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Description = "Small distribution order for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0003",
                            Status = 3,
                            SubmittedAtUtc = new DateTime(2026, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 24347.83m,
                            Title = "Small distribution order",
                            TotalAmount = 28000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 3652.17m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000004"),
                            AssignedAtUtc = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 2,
                            AssignedToUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTime(2026, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Description = "Fiber Retail service package for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0004",
                            Status = 3,
                            SubmittedAtUtc = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 39130.43m,
                            Title = "Fiber Retail service package",
                            TotalAmount = 45000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 5869.57m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000005"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssignedAtUtc = new DateTime(2026, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 3,
                            AssignedToUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUtc = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            Description = "Platform implementation advance for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0005",
                            Status = 4,
                            SubmittedAtUtc = new DateTime(2026, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 108695.65m,
                            Title = "Platform implementation advance",
                            TotalAmount = 125000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 16304.35m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000006"),
                            AssignedAtUtc = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 2,
                            AssignedToUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTime(2026, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Description = "Metro Logistics annual support for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0006",
                            Status = 3,
                            SubmittedAtUtc = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 156521.74m,
                            Title = "Metro Logistics annual support",
                            TotalAmount = 180000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 23478.26m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000007"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssignedAtUtc = new DateTime(2026, 1, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 3,
                            AssignedToUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUtc = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            Description = "Enterprise procurement billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0007",
                            Status = 4,
                            SubmittedAtUtc = new DateTime(2026, 1, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 217391.30m,
                            Title = "Enterprise procurement billing",
                            TotalAmount = 250000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 32608.70m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000008"),
                            AssignedAtUtc = new DateTime(2026, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 1,
                            AssignedToUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 1, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            Description = "Northstar revised billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            RejectedAtUtc = new DateTime(2026, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0008",
                            Status = 6,
                            SubmittedAtUtc = new DateTime(2026, 1, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 56521.74m,
                            Title = "Northstar revised billing",
                            TotalAmount = 65000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 8478.26m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000009"),
                            AssignedAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 1,
                            AssignedToUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 1, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Description = "Greenline returned billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            RejectedAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0009",
                            Status = 6,
                            SubmittedAtUtc = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 30434.78m,
                            Title = "Greenline returned billing",
                            TotalAmount = 35000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 4565.22m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000010"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApprovedAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            Description = "BluePeak subscription billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0010",
                            Status = 7,
                            SubmittedAtUtc = new DateTime(2026, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 45217.39m,
                            Title = "BluePeak subscription billing",
                            TotalAmount = 52000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 6782.61m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000011"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApprovedAtUtc = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Description = "Fiber Retail replenishment for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0011",
                            Status = 7,
                            SubmittedAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 80000m,
                            Title = "Fiber Retail replenishment",
                            TotalAmount = 92000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 12000m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000012"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApprovedAtUtc = new DateTime(2026, 1, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Description = "Metro Logistics freight billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0012",
                            Status = 7,
                            SubmittedAtUtc = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 73913.04m,
                            Title = "Metro Logistics freight billing",
                            TotalAmount = 85000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 11086.96m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000013"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApprovedAtUtc = new DateTime(2026, 1, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            Description = "Eastern Trading supply billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            ManagerReviewedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RequestNumber = "BR-2026-0013",
                            Status = 7,
                            SubmittedAtUtc = new DateTime(2026, 1, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 121739.13m,
                            Title = "Eastern Trading supply billing",
                            TotalAmount = 140000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 18260.87m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000014"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApprovedAtUtc = new DateTime(2026, 1, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            Description = "Northstar completion billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0014",
                            Status = 8,
                            SubmittedAtUtc = new DateTime(2026, 1, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 27826.09m,
                            Title = "Northstar completion billing",
                            TotalAmount = 32000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 4173.91m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000015"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApprovedAtUtc = new DateTime(2026, 1, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Description = "Greenline delivery billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0015",
                            Status = 8,
                            SubmittedAtUtc = new DateTime(2026, 1, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 76521.74m,
                            Title = "Greenline delivery billing",
                            TotalAmount = 88000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 11478.26m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000016"),
                            AccountsReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApprovedAtUtc = new DateTime(2026, 1, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            AssignedQueue = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            Description = "BluePeak enterprise billing for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            ManagerReviewedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RequestNumber = "BR-2026-0016",
                            Status = 8,
                            SubmittedAtUtc = new DateTime(2026, 1, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            SubmittedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubtotalAmount = 304347.83m,
                            Title = "BluePeak enterprise billing",
                            TotalAmount = 350000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 45652.17m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000017"),
                            AssignedQueue = 0,
                            CreatedAtUtc = new DateTime(2026, 1, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Description = "Cancelled duplicate request for seeded workflow testing.",
                            LastWorkflowActionAtUtc = new DateTime(2026, 1, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            RequestNumber = "BR-2026-0017",
                            Status = 9,
                            SubtotalAmount = 34782.61m,
                            Title = "Cancelled duplicate request",
                            TotalAmount = 40000m,
                            UpdatedAtUtc = new DateTime(2026, 1, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            VatAmount = 5217.39m
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.BillingRequestLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillingRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillingRequestId");

                    b.ToTable("BillingRequestLineItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000001"),
                            Description = "Retail starter billing line item",
                            LineTotal = 10434.78m,
                            Quantity = 1,
                            UnitPrice = 10434.78m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000002"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000002"),
                            Description = "Monthly logistics support line item",
                            LineTotal = 67826.09m,
                            Quantity = 1,
                            UnitPrice = 67826.09m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000003"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000003"),
                            Description = "Small distribution order line item",
                            LineTotal = 24347.83m,
                            Quantity = 1,
                            UnitPrice = 24347.83m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000004"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000004"),
                            Description = "Fiber Retail service package line item",
                            LineTotal = 39130.43m,
                            Quantity = 1,
                            UnitPrice = 39130.43m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000005"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000005"),
                            Description = "Platform implementation advance line item",
                            LineTotal = 108695.65m,
                            Quantity = 1,
                            UnitPrice = 108695.65m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000006"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000006"),
                            Description = "Metro Logistics annual support line item",
                            LineTotal = 156521.74m,
                            Quantity = 1,
                            UnitPrice = 156521.74m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000007"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000007"),
                            Description = "Enterprise procurement billing line item",
                            LineTotal = 217391.30m,
                            Quantity = 1,
                            UnitPrice = 217391.30m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000008"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000008"),
                            Description = "Northstar revised billing line item",
                            LineTotal = 56521.74m,
                            Quantity = 1,
                            UnitPrice = 56521.74m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000009"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000009"),
                            Description = "Greenline returned billing line item",
                            LineTotal = 30434.78m,
                            Quantity = 1,
                            UnitPrice = 30434.78m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000010"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000010"),
                            Description = "BluePeak subscription billing line item",
                            LineTotal = 45217.39m,
                            Quantity = 1,
                            UnitPrice = 45217.39m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000011"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000011"),
                            Description = "Fiber Retail replenishment line item",
                            LineTotal = 80000m,
                            Quantity = 1,
                            UnitPrice = 80000m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000012"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000012"),
                            Description = "Metro Logistics freight billing line item",
                            LineTotal = 73913.04m,
                            Quantity = 1,
                            UnitPrice = 73913.04m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000013"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000013"),
                            Description = "Eastern Trading supply billing line item",
                            LineTotal = 121739.13m,
                            Quantity = 1,
                            UnitPrice = 121739.13m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000014"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000014"),
                            Description = "Northstar completion billing line item",
                            LineTotal = 27826.09m,
                            Quantity = 1,
                            UnitPrice = 27826.09m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000015"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000015"),
                            Description = "Greenline delivery billing line item",
                            LineTotal = 76521.74m,
                            Quantity = 1,
                            UnitPrice = 76521.74m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000016"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000016"),
                            Description = "BluePeak enterprise billing line item",
                            LineTotal = 304347.83m,
                            Quantity = 1,
                            UnitPrice = 304347.83m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000017"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000017"),
                            Description = "Cancelled duplicate request line item",
                            LineTotal = 34782.61m,
                            Quantity = 1,
                            UnitPrice = 34782.61m
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillingRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("BillingRequestId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-000000000001"),
                            AuthorUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000008"),
                            Body = "Rejected pending corrected purchase order.",
                            CreatedAtUtc = new DateTime(2026, 1, 13, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-000000000002"),
                            AuthorUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000009"),
                            Body = "Rejected because billed amount needs clarification.",
                            CreatedAtUtc = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-000000000003"),
                            AuthorUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000006"),
                            Body = "High-value request needs management approval after accounts review.",
                            CreatedAtUtc = new DateTime(2026, 1, 11, 13, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxIdentifier")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            BillingAddress = "House 11, Road 7, Dhaka",
                            ContactEmail = "billing@fiberretail.local",
                            ContactPerson = "Nadia Rahman",
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fiber Retail Ltd.",
                            Phone = "+8801700000001",
                            Status = 1,
                            TaxIdentifier = "TIN-FIBER-001",
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            BillingAddress = "Port Road, Chattogram",
                            ContactEmail = "finance@metrologistics.local",
                            ContactPerson = "Tariq Hasan",
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Metro Logistics Bangladesh",
                            Phone = "+8801700000002",
                            Status = 1,
                            TaxIdentifier = "TIN-METRO-002",
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            BillingAddress = "Airport Road, Dhaka",
                            ContactEmail = "accounts@northstar.local",
                            ContactPerson = "Rumana Islam",
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Northstar Enterprise",
                            Phone = "+8801700000003",
                            Status = 1,
                            TaxIdentifier = "TIN-NORTH-003",
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            BillingAddress = "Industrial Area, Gazipur",
                            ContactEmail = "billing@greenline.local",
                            ContactPerson = "Farhan Kabir",
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Greenline Distribution",
                            Phone = "+8801700000004",
                            Status = 1,
                            TaxIdentifier = "TIN-GREEN-004",
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            BillingAddress = "Banani, Dhaka",
                            ContactEmail = "finance@bluepeak.local",
                            ContactPerson = "Mahira Chowdhury",
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "BluePeak Systems",
                            Phone = "+8801700000005",
                            Status = 1,
                            TaxIdentifier = "TIN-BLUE-005",
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            BillingAddress = "Motijheel, Dhaka",
                            ContactEmail = "accounts@easterntrading.local",
                            ContactPerson = "Sabbir Ahmed",
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Eastern Trading Co.",
                            Phone = "+8801700000006",
                            Status = 1,
                            TaxIdentifier = "TIN-EAST-006",
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.EnrollmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RequestedRole")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Email");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("EnrollmentRequests", (string)null);
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillingRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DueDays")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillingRequestId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Invoices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000010"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            DueAtUtc = new DateTime(2026, 2, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDays = 30,
                            InvoiceNumber = "INV-2026-0001",
                            IssuedAtUtc = new DateTime(2026, 1, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            SubtotalAmount = 45217.39m,
                            TotalAmount = 52000m,
                            VatAmount = 6782.61m,
                            VatPercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000011"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            DueAtUtc = new DateTime(2026, 2, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDays = 30,
                            InvoiceNumber = "INV-2026-0002",
                            IssuedAtUtc = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            SubtotalAmount = 80000m,
                            TotalAmount = 92000m,
                            VatAmount = 12000m,
                            VatPercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000003"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000012"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            DueAtUtc = new DateTime(2026, 2, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDays = 30,
                            InvoiceNumber = "INV-2026-0003",
                            IssuedAtUtc = new DateTime(2026, 1, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            SubtotalAmount = 73913.04m,
                            TotalAmount = 85000m,
                            VatAmount = 11086.96m,
                            VatPercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000004"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000013"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            DueAtUtc = new DateTime(2026, 2, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDays = 30,
                            InvoiceNumber = "INV-2026-0004",
                            IssuedAtUtc = new DateTime(2026, 1, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            SubtotalAmount = 121739.13m,
                            TotalAmount = 140000m,
                            VatAmount = 18260.87m,
                            VatPercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000005"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000014"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            DueAtUtc = new DateTime(2026, 2, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDays = 30,
                            InvoiceNumber = "INV-2026-0005",
                            IssuedAtUtc = new DateTime(2026, 1, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            PaidAtUtc = new DateTime(2026, 1, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            SubtotalAmount = 27826.09m,
                            TotalAmount = 32000m,
                            VatAmount = 4173.91m,
                            VatPercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000006"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000015"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            DueAtUtc = new DateTime(2026, 2, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDays = 30,
                            InvoiceNumber = "INV-2026-0006",
                            IssuedAtUtc = new DateTime(2026, 1, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            PaidAtUtc = new DateTime(2026, 1, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            SubtotalAmount = 76521.74m,
                            TotalAmount = 88000m,
                            VatAmount = 11478.26m,
                            VatPercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000007"),
                            BillingRequestId = new Guid("99999999-9999-9999-9999-000000000016"),
                            CustomerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            DueAtUtc = new DateTime(2026, 2, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDays = 30,
                            InvoiceNumber = "INV-2026-0007",
                            IssuedAtUtc = new DateTime(2026, 1, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            PaidAtUtc = new DateTime(2026, 1, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            SubtotalAmount = 304347.83m,
                            TotalAmount = 350000m,
                            VatAmount = 45652.17m,
                            VatPercentage = 15m
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "BR-2026-0004 is waiting for Accounts review.",
                            Title = "Request ready for review",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "BR-2026-0007 is waiting for Management approval.",
                            Title = "Manager approval needed",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 1, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "BR-2026-0008 needs revision.",
                            Title = "Request rejected",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeactivatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<Guid?>("EnrollmentRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sales@flowledger.local",
                            FullName = "Sarah Sales",
                            IsActive = true,
                            PasswordHash = "",
                            PasswordSalt = "",
                            Role = 1,
                            Status = 1,
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "accounts@flowledger.local",
                            FullName = "Amir Accounts",
                            IsActive = true,
                            PasswordHash = "",
                            PasswordSalt = "",
                            Role = 2,
                            Status = 1,
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@flowledger.local",
                            FullName = "Mona Manager",
                            IsActive = true,
                            PasswordHash = "",
                            PasswordSalt = "",
                            Role = 3,
                            Status = 1,
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@flowledger.local",
                            FullName = "Adam Admin",
                            IsActive = true,
                            PasswordHash = "",
                            PasswordSalt = "",
                            Role = 4,
                            Status = 1,
                            UpdatedAtUtc = new DateTime(2026, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultDashboardPeriodMonths")
                        .HasColumnType("int");

                    b.Property<string>("DefaultLandingPage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("RowsPerPage")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("FlowLedger.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowLedger.Domain.Entities.BillingRequest", "BillingRequest")
                        .WithMany("AuditLogs")
                        .HasForeignKey("BillingRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ActorUser");

                    b.Navigation("BillingRequest");
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.BillingRequest", b =>
                {
                    b.HasOne("FlowLedger.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlowLedger.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowLedger.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.BillingRequestLineItem", b =>
                {
                    b.HasOne("FlowLedger.Domain.Entities.BillingRequest", "BillingRequest")
                        .WithMany("LineItems")
                        .HasForeignKey("BillingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingRequest");
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.Comment", b =>
                {
                    b.HasOne("FlowLedger.Domain.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowLedger.Domain.Entities.BillingRequest", "BillingRequest")
                        .WithMany("Comments")
                        .HasForeignKey("BillingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("BillingRequest");
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.EnrollmentRequest", b =>
                {
                    b.HasOne("FlowLedger.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("FlowLedger.Domain.Entities.BillingRequest", "BillingRequest")
                        .WithOne("Invoice")
                        .HasForeignKey("FlowLedger.Domain.Entities.Invoice", "BillingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowLedger.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingRequest");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FlowLedger.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("FlowLedger.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowLedger.Domain.Entities.BillingRequest", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Comments");

                    b.Navigation("Invoice");

                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
